export const DEFAULT_ERROR_CODE = 'UNKNOWN_ERROR';

export const ErrorCode = {
  // ===== DEFAULT =====
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',

  // ===== AUTH =====
  NO_TOKEN: 'NO_TOKEN',
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  REFRESH_TOKEN_EXPIRED: 'REFRESH_TOKEN_EXPIRED',
  EMAIL_ALREADY_VERIFIED: 'EMAIL_ALREADY_VERIFIED',
  EMAIL_ALREADY_REGISTERED_NOT_VERIFIED: 'EMAIL_ALREADY_REGISTERED_NOT_VERIFIED',

  // ===== PERMISSION =====
  FORBIDDEN: 'FORBIDDEN',

  // ===== CSRF =====
  CSRF_TOKEN_MISSING: 'CSRF_TOKEN_MISSING',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  CSRF_TOKEN_EXPIRED: 'CSRF_TOKEN_EXPIRED',

  // ===== VALIDATION =====
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // ===== RESOURCE =====
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
