export const APP_FEATURES = [
  {
    id: '01',
    title: 'Tailored Just for You',
    description:
      'Get interview questions and model answers based on your role, experience, and specific focus areas – no',
  },
  {
    id: '02',
    title: 'Learn at Your Own Pace',
    description:
      "Expand answers only when you're ready. Dive deeper into any concept instantly with AI-powered detailed e",
  },
  {
    id: '03',
    title: 'Capture Your Insights',
    description:
      'Add personal notes to any question and pin important ones to the top – making your learning more organiz',
  },
  {
    id: '04',
    title: 'Understand the "Why" Behind Answers',
    description:
      'Beyond just answers – unlock detailed concept explanations generated by AI, helping you truly master each',
  },
  {
    id: '05',
    title: 'Save, Organize, and Revisit',
    description:
      'Easily save your interview sets, organize them neatly in your dashboard, and pick up your preparation ri',
  },
];

const bodyQuestion =
  '[\n  {\n    "question": "Explain the difference between controlled and uncontrolled components in React. When would you use each, and provide a simple example of a controlled input?",\n    "answer": "Controlled components are form elements (like input, textarea, select) whose value is managed by React state. The component\'s value is set via props (usually from useState) and updated via onChange handlers. Uncontrolled components manage their own internal state in the DOM; you access their current value with refs when needed (e.g., on form submit).\\n\\nWhen to use each:\\n- Controlled: Preferred in most React apps when you need instant validation, conditional UI, or to keep form state in sync with other parts of the app. It offers predictable data flow and easier testing.\\n- Uncontrolled: Useful for simple forms where you don\'t need to update or validate on every change, or when integrating with non-React libraries. It can be slightly simpler and perform a bit better for very large forms.\\n\\nExample of a simple controlled input:\\n\\nconst { useState } = React;\\n\\nfunction NameForm() {\\n  const [name, setName] = useState(\'\');\\n\\n  function handleChange(e) {\\n    setName(e.target.value);\\n  }\\n\\n  function handleSubmit(e) {\\n    e.preventDefault();\\n    alert(\'Submitted name: \' + name);\\n  }\\n\\n  return (\\n    <form onSubmit={handleSubmit}>\\n      <label>\\n        Name:\\n        <input type=\\"text\\" value={name} onChange={handleChange} />\\n      </label>\\n      <button type=\\"submit\\">Submit</button>\\n    </form>\\n  );\\n}\\n\\nThis component keeps the input value in React state (name). The input\'s value prop is always derived from state, and onChange updates that state, making it a controlled component."\n  }\n]';

console.log(JSON.parse(bodyQuestion));
